"""empty message

Revision ID: 6a779a751846
Revises: 7f29be3196c7
Create Date: 2017-12-29 20:52:48.144252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a779a751846'
down_revision = '7f29be3196c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('front_user', sa.Column('join_time', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'front_user', ['telephone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'front_user', type_='unique')
    op.drop_column('front_user', 'join_time')
    op.drop_table('board')
    # ### end Alembic commands ###
