"""empty message

Revision ID: 89722590f5ef
Revises: adb6372d5967
Create Date: 2018-01-10 12:17:04.527177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89722590f5ef'
down_revision = 'adb6372d5967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cms_role', 'desc',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('front_user', 'telephone',
               existing_type=mysql.VARCHAR(length=11),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('front_user', 'telephone',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('cms_role', 'desc',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
