"""empty message

Revision ID: 9584f5bd5b71
Revises: 6a8915ffd845
Create Date: 2018-01-10 11:45:25.388847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9584f5bd5b71'
down_revision = '6a8915ffd845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('qq', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'qq')
    # ### end Alembic commands ###
