"""empty message

Revision ID: eb3ff736c93f
Revises: f7b2b539802c
Create Date: 2018-01-03 22:53:48.341371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3ff736c93f'
down_revision = 'f7b2b539802c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author_id', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'comment', 'front_user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'author_id')
    # ### end Alembic commands ###
