"""add country column

Revision ID: 8a0638123e1f
Revises: a6fa3751a8a4
Create Date: 2017-11-03 15:59:58.449296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0638123e1f'
down_revision = 'a6fa3751a8a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'country')
    # ### end Alembic commands ###
