"""empty message

Revision ID: f476148dc2a9
Revises: a5c3549a12dc
Create Date: 2017-10-08 21:02:16.093630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f476148dc2a9'
down_revision = 'a5c3549a12dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('valid_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'valid_time')
    # ### end Alembic commands ###
